# Generated by Django 6.0.6 on 2026-07-10 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('profession_base', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('etudes_faites', models.TextField()),
                ('cv', models.FileField(upload_to='cv_consultants/')),
                ('fonction_occupee', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bon', models.CharField(max_length=50, verbose_name='Numéro de Bon')),
                ('provenance', models.CharField(max_length=200)),
                ('montant_recu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.TextField()),
                ('no_contrat', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EtatBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_etat_besoin', models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° État de besoin')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('projet_demandeur', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('no_bon', models.CharField(max_length=50, unique=True)),
                ('piece_jointe', models.FileField(upload_to='justificatifs/')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=200)),
                ('terme_reference', models.FileField(upload_to='tdr/')),
                ('duree_mission', models.CharField(max_length=100)),
                ('bailleur_fond', models.CharField(max_length=200)),
                ('zone_intervention', models.CharField(max_length=255)),
                ('document_proposition', models.FileField(blank=True, null=True, upload_to='propositions/')),
                ('est_soumise', models.BooleanField(default=False)),
                ('est_validee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bon', models.CharField(max_length=50, verbose_name='Numéro de Bon')),
                ('projet', models.CharField(max_length=200)),
                ('nom_beneficiaire', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=100)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.TextField()),
                ('no_ordre_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observation', models.TextField(blank=True)),
                ('etat_besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.etatbesoin')),
            ],
        ),
        migrations.CreateModel(
            name='DetailJustificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.justificatif')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Présent', 'Présent'), ('Absent', 'Absent'), ('Congé', 'Congé')], max_length=20)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.consultant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du Projet')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projets/logos/', verbose_name='Logo du Projet')),
                ('bailleur_fond', models.CharField(max_length=200, verbose_name='Bailleur de Fonds')),
                ('no_contrat', models.CharField(max_length=100, verbose_name='N° Contrat Projet & AMAR')),
                ('cout_global', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Coût Global')),
                ('zone_intervention', models.CharField(max_length=255, verbose_name="Zone d'intervention")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('chef_projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_titre', models.CharField(max_length=200)),
                ('activite_prevue', models.TextField()),
                ('activite_realisee', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('zone_intervention', models.CharField(max_length=255)),
                ('observation', models.TextField(blank=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/photos/')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('numero_piece', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('provenance_beneficiaire', models.CharField(blank=True, max_length=255, null=True)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='MaterielNonConsommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('no_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('Neuf', 'Neuf'), ('Bon', 'Bon'), ('Usagé', 'Usagé')], max_length=50)),
                ('date_achat', models.DateField()),
                ('imputation', models.CharField(max_length=100)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ElementProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='projets/documents/')),
                ('type_element', models.CharField(choices=[('RAPPORT', 'Rapport'), ('LIVRABLE', 'Livrable'), ('AUTRE', 'Autre')], max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='dashboard.projet')),
            ],
        ),
        migrations.AddField(
            model_name='consultant',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultants', to='dashboard.projet'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taches_principales', models.TextField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.consultant')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='RapportProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Livrable', 'Livrable'), ('Mission', 'Mission'), ('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Final', 'Final')], max_length=20)),
                ('fichier', models.FileField(upload_to='projets/rapports/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='TermeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('zone_intervention', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='tdr/')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdrs', to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='RapportMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('zone_intervention', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('observation_se', models.TextField(blank=True, verbose_name='Observation Responsable S&E')),
                ('tdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='dashboard.termereference')),
            ],
        ),
    ]
