# Generated by Django 6.1 on 2026-08-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planification",
            name="observation",
        ),
        migrations.AlterField(
            model_name="planification",
            name="activite_prevue",
            field=models.TextField(verbose_name="Activité prévues"),
        ),
        migrations.AlterField(
            model_name="planification",
            name="activite_realisee",
            field=models.TextField(
                blank=True, null=True, verbose_name="Activités réalisées"
            ),
        ),
        migrations.AlterField(
            model_name="planification",
            name="date_debut",
            field=models.DateField(verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="planification",
            name="date_fin",
            field=models.DateField(verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="planification",
            name="mission_titre",
            field=models.CharField(max_length=200, verbose_name="Titre de la mission"),
        ),
        migrations.AlterField(
            model_name="planification",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planifications",
                to="dashboard.projet",
                verbose_name="Projet concerné",
            ),
        ),
        migrations.AlterField(
            model_name="planification",
            name="zone_intervention",
            field=models.CharField(max_length=255, verbose_name="Zone d'intervention"),
        ),
        migrations.AlterField(
            model_name="projet",
            name="no_contrat",
            field=models.CharField(
                max_length=100, verbose_name="N° Contrat Projet & Avolar"
            ),
        ),
    ]
