# Generated by Django 6.1 on 2026-08-18 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_planification_observation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaireTerrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=200, verbose_name="Titre du formulaire"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulaires_terrain",
                        to="dashboard.projet",
                        verbose_name="Projet associé",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampFormulaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle_champ",
                    models.CharField(
                        max_length=200, verbose_name="Libellé de la question"
                    ),
                ),
                (
                    "type_champ",
                    models.CharField(
                        choices=[
                            ("text", "Champ texte court"),
                            ("textarea", "Champ texte long"),
                            ("number", "Champ chiffre"),
                            ("date", "Champ date"),
                            ("select", "Choix multiple / Liste déroulante"),
                            ("checkbox", "Case à cocher"),
                            ("photo", "Champ photo (Appareil / Fichier)"),
                            ("gps", "Coordonnées GPS (Géolocalisation)"),
                        ],
                        max_length=50,
                        verbose_name="Type de champ",
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Options (séparées par des virgules pour les choix multiples)",
                    ),
                ),
                (
                    "obligatoire",
                    models.BooleanField(
                        default=False, verbose_name="Champ obligatoire"
                    ),
                ),
                (
                    "formulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champs",
                        to="dashboard.formulaireterrain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoumissionDonnee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "donnees_json",
                    models.JSONField(verbose_name="Données collectées (JSON)"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent collecteur",
                    ),
                ),
                (
                    "formulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soumissions",
                        to="dashboard.formulaireterrain",
                    ),
                ),
            ],
        ),
    ]
