# Generated by Django 6.1 on 2026-08-19 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_formulaireterrain_champformulaire_soumissiondonnee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="champformulaire",
            name="libelle_champ",
        ),
        migrations.RemoveField(
            model_name="champformulaire",
            name="obligatoire",
        ),
        migrations.AddField(
            model_name="champformulaire",
            name="est_obligatoire",
            field=models.BooleanField(default=True, verbose_name="Champ obligatoire"),
        ),
        migrations.AddField(
            model_name="champformulaire",
            name="libelle_question",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Question / Intitulé du champ"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="champformulaire",
            name="ordre",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="champformulaire",
            name="options",
            field=models.TextField(
                blank=True, help_text="Séparez les options par une virgule.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="champformulaire",
            name="type_champ",
            field=models.CharField(
                choices=[
                    ("texte", "Texte court"),
                    ("texte_long", "Texte long (Paragraphe)"),
                    ("nombre", "Chiffre / Nombre"),
                    ("date", "Date"),
                    ("heure", "Heure"),
                    ("choix_unique", "Sélection / Choix unique"),
                    ("choix_multiple", "Cases à cocher (Choix multiple)"),
                    ("gps", "Coordonnées GPS (Géolocalisation)"),
                    ("photo", "Photo (Appareil ou Importation)"),
                    ("signature", "Signature numérique"),
                ],
                max_length=50,
                verbose_name="Type de réponse",
            ),
        ),
        migrations.AlterField(
            model_name="formulaireterrain",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formulaires",
                to="dashboard.projet",
                verbose_name="Projet associé",
            ),
        ),
        migrations.AlterField(
            model_name="formulaireterrain",
            name="titre",
            field=models.CharField(max_length=255, verbose_name="Titre du formulaire"),
        ),
    ]
